# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  yarn_install:
    docker:
      - image: circleci/node:11.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save node_modules
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  yarn_test:
    docker:
      - image: circleci/node:11.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Running test and creating coverage
          command: yarn test:coverage
workflows:
  version: 2
  test_and_coverage:
    jobs:
      - yarn_install
      - yarn_test:
          requires:
            - yarn_install
